pipeline {
    agent any
    stages {
        stage('Init') {
            steps {
                echo 'Git Pull...'
                retry(3) {
                    sh 'git pull origin master'
                }
            }
        }
        stage('Build') {
            def mvn_version = 'M3Local'
            withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
                steps {
                    echo 'MVN Build...'
                    dir('services/general_srv/general_srv_config_server') {
                        sh 'mvn clean package -DskipTests dockerfile:build'
                    }
                }
            }
        }
        /*stage('Test') {
            steps {
                echo 'Test...'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }*/
        stage('Deploy') {
            steps {
                echo 'Deploy...'
                sh './helpers/deploy_docker_image.sh localhost test general_srv_config_server 18888 1.0.1 liuhongye2018 A1987719'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
            /*mail to: 'liujiaqi@zlycare.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: "Something is wrong with ${env.BUILD_URL}"*/
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
