test:
  name: "this is ad service test"
  property: "property from config server test"
  hi: "hello config server test"

spring:
  data:
    mongodb:
      uri: mongodb://opadmin:opadmin_2016@dds-2zecda7e082ebb241641-pub.mongodb.rds.aliyuncs.com:3717,dds-2zecda7e082ebb242806-pub.mongodb.rds.aliyuncs.com:3717/zlydata?replicaSet=mgset-2628167
debug: true
info:
  profile: default asdsadd234234klsdfksdjfksdsdfsd33
