server:
  port: 18888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/zlycare/juliye_ms_config_server
                    searchPaths: [src/main/resources/config/adservice,src/main/resources/config/bossservice]
                    # searchPaths: src/main/resources/config/*service/*
                    username: ${github_username}
                    password: ${github_password}

logging:
  path: /data/logs/juliye_ms_config_server
  file: /data/logs/juliye_ms_config_server/juliye_ms_config_server.log
  level:
     root: info