server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: "file:///Users/Jacky/Workspaces/Juliye/care/juliye_ms_config_server/src/main/resources/config/adservice"