server:
  port: 18888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/liujiaqiid/cloud_micro_srv_boot
                    searchPaths: [assets]
                    username: ${github_username}
                    password: ${github_password}

logging:
  path: /data/logs/general_srv_config_server
  file: /data/logs/general_srv_config_server/general_srv_config_server.log
  level:
     root: info